// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed:
      "sh -c 'rm -rf /tmp/havenretreat-prisma-seed && npx tsc -p prisma/tsconfig.seed.json --outDir /tmp/havenretreat-prisma-seed && node /tmp/havenretreat-prisma-seed/seed.js'",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
