// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "env TS_NODE_PROJECT=prisma/tsconfig.seed.json node --loader ts-node/esm prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
