DELETE FROM "CouponRule"
WHERE "type"::text IN ('SLOT_ID');

ALTER TYPE "CouponRuleType" RENAME TO "CouponRuleType_old";

CREATE TYPE "CouponRuleType" AS ENUM (
  'BOOKING_DATE_RANGE',
  'BOOKING_TIME_RANGE',
  'BOOKING_DURATION_MIN',
  'CATEGORY',
  'PRODUCT_ID',
  'USER_ID',
  'TARGET_CATEGORY',
  'TARGET_PRODUCT_ID',
  'DECORATION_REQUIRED'
);

ALTER TABLE "CouponRule"
ALTER COLUMN "type" TYPE "CouponRuleType"
USING (
  CASE "type"::text
    WHEN 'SLOT_DATE_RANGE' THEN 'BOOKING_DATE_RANGE'
    WHEN 'SLOT_TIME_RANGE' THEN 'BOOKING_TIME_RANGE'
    WHEN 'SLOT_DURATION_MIN' THEN 'BOOKING_DURATION_MIN'
    ELSE "type"::text
  END
)::"CouponRuleType";

DROP TYPE "CouponRuleType_old";
